version: "3.8"

services:
  app:
    networks:
      - quotesApi-network
    build: .
    restart: on-failure
    ports:
      - "8081:8081"
    volumes:
      - .m2:/root/.m2

volumes:
  dbvol:

networks:
  quotesApi-network:
    driver: bridge